export default function() {

  // These comments are here to help you get started. Feel free to delete them.

  /*
    Config (with defaults).

    Note: these only affect routes defined *after* them!
  */

  // this.urlPrefix = '';    // make this `http://localhost:8080`, for example, if your API is on a different server
     this.namespace = '/api';    // make this `/api`, for example, if your API is namespaced
  // this.timing = 400;      // delay for each request, automatically set to 0 during testing

  /*
    Shorthand cheatsheet:

    this.get('/posts');
    this.post('/posts');
    this.get('/posts/:id');
    this.put('/posts/:id'); // or this.patch
    this.del('/posts/:id');

    http://www.ember-cli-mirage.com/docs/v0.3.x/shorthands/
  */
  
  //let get started pliz... 
  
  //static way.... hello world stuff.
  //https://api.akvo.org/flow/orgs/<organization-subdomain>/data-points/<surveyId>
  //GET /api/dataPoints/surveyId. ===> retrieving the dataPoints basing on the surveyId.
   this.get('/api/dataPoints', function(){
      return {
        dataPoints:[  //pliz a find  a way to configure this..
          {
	          id: "23124",
	          displayName: "foo",
	          identifier: "fkdos-dso-dofks",
	          latitude: 56.2,
	          longitude: 23.6,
	          createdAt: "2017-02-23T03:30:58",
	          modifiedAt: "2017-02-23T03:30:58",
            surveyId: '123' //matching teh survey selected.
	      },
        {
          id: "23124",
          displayName: "foo",
          identifier: "fkdos-dso-dofks",
          latitude: 56.2,
          longitude: 23.6,
          createdAt: "2017-02-23T03:30:58",
          modifiedAt: "2017-02-23T03:30:58",
          surveyId: '123' //matching teh survey selected.
        },
       {
        id: "23124",
        displayName: "foo",
        identifier: "fkdos-dso-dofks",
        latitude: 56.2,
        longitude: 23.6,
        createdAt: "2017-02-23T03:30:58",
        modifiedAt: "2017-02-23T03:30:58",
        surveyId: '123' //matching teh survey selected.
          }    
        ]
      }//end of the return statement
   }) //route handler... for  GET /api/dataPoints/ but later u shall change it to FLOW.placemark
  
  // retreieving the list of form responses..Retrieving form responses
  //https://api.akvo.org/flow/orgs/<organization-subdomain>/form-instances/<survey-id>/<form-id>
   this.get('/form-instances', function(){
      return {
        formInstances:[
          {
            id: "3456",
            dataPointId: "4567",
            identifier: "hxeq-lb2e-g1n2",
            displayName: "",
            deviceIdentifier: "foo",
            submissionDate: "2017-02-23T03:30:58",
            submitter: "John",
            duration: 123,
            responses: {}
          },
          {
            id: "3456",
            dataPointId: "4567",
            identifier: "hxeq-lb2e-g1n2",
            displayName: "",
            deviceIdentifier: "foo",
            submissionDate: "2017-02-23T03:30:58",
            submitter: "John",
            duration: 123,
            responses: {}
          },
          {
            id: "3456",
            dataPointId: "4567",
            identifier: "hxeq-lb2e-g1n2",
            displayName: "",
            deviceIdentifier: "foo",
            submissionDate: "2017-02-23T03:30:58",
            submitter: "John",
            duration: 123,
            responses: {}
          }
        ]
      }
   }) //route handler for form-instances.
   
     //this is what is autogenerated from the server side.. by mulo.
     //the maps use a different one   ===> /rest/placemarks
      this.get('/placemarks', function(){ //why should it be plural
         return {
           data: [
             { 
               type: 'placemarks',
               id: '1234',
               attributes:{
                 collectionDate: 1400077495009, 
                 count: 1, 
                 detailsId: 8943078, 
                 keyId: 17886156, 
                 latitude: -11.334335, 
                 level: 0, 
                 longitude: -49.251078, 
                 markType: null, 
                 surveyId: 125001
               }
            }, 
            { 
              type: 'placemarks',
              id: '1235',
              attributes:{
                collectionDate: 1400233173034, 
                count: 1, 
                detailsId: 8943137, 
                keyId: 17886274, 
                latitude: -11.334335, 
                level: 0, 
                longitude: -49.251078, 
                markType: null, 
                surveyId: 13774000
              }
            }, 
            {
             type: 'placemarks',
             id: '1236',
             attributes:{
               collectionDate: 1401103333327, 
               count: 1, 
               detailsId: 14933165, 
               keyId: 29866330, 
               latitude: -11.334335, 
               level: 0, 
               longitude: -49.251078, 
               markType: null, 
               surveyId: 13774000
             }     
           }, 
           {
             type: 'placemarks',
             id: '1237',
             attributes:{
                collectionDate: 1400077480329, 
                 count: 1, 
                 detailsId: 16933071, 
                 keyId: 33866142, 
                 latitude: -11.334335, 
                 level: 0, 
                 longitude: -49.251078, 
                 markType: null, 
                 surveyId: 125001
             }
            }
           ]
         }
      })
}
